### ISSUE TITLE
"still pending" Warnungen

### ISSUE THREAD

**Issue by daniel-lo** [ioBroker/ioBroker.hm-rega#101]
Hallo, mein Log ist seit Neustem voll von diesen Meldungen .. gibt es Abhilfe? Schönen Gruß

hm-rega.0 | 2020-05-26 05:44:59.686 | warn | (1215) Script "!# programs.fn 1.3 !# Dieses Script gibt eine Liste der  Programme als JSON Strin" ignored, because still pending.
-- | -- | -- | --
hm-rega.0 | 2020-05-26 05:44:59.644 | warn | (1215) Script "!# polling.fn 1.2 !# !# Dieses Script gibt die Werte  aller Systemvariablen als J" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:44:29.686 | warn | (1215) Script "!# programs.fn 1.3 !# Dieses Script gibt eine Liste der  Programme als JSON Strin" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:44:29.644 | warn | (1215) Script "!# polling.fn 1.2 !# !# Dieses Script gibt die Werte  aller Systemvariablen als J" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:43:59.686 | warn | (1215) Script "!# programs.fn 1.3 !# Dieses Script gibt eine Liste der  Programme als JSON Strin" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:43:59.643 | warn | (1215) Script "!# polling.fn 1.2 !# !# Dieses Script gibt die Werte  aller Systemvariablen als J" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:43:29.686 | warn | (1215) Script "!# programs.fn 1.3 !# Dieses Script gibt eine Liste der  Programme als JSON Strin" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:43:29.642 | warn | (1215) Script "!# polling.fn 1.2 !# !# Dieses Script gibt die Werte  aller Systemvariablen als J" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:42:59.686 | warn | (1215) Script "!# programs.fn 1.3 !# Dieses Script gibt eine Liste der  Programme als JSON Strin" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:42:59.642 | warn | (1215) Script "!# polling.fn 1.2 !# !# Dieses Script gibt die Werte  aller Systemvariablen als J" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:42:29.682 | warn | (1215) Script "!# programs.fn 1.3 !# Dieses Script gibt eine Liste der  Programme als JSON Strin" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:42:29.640 | warn | (1215) Script "!# polling.fn 1.2 !# !# Dieses Script gibt die Werte  aller Systemvariablen als J" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:41:59.682 | warn | (1215) Script "!# programs.fn 1.3 !# Dieses Script gibt eine Liste der  Programme als JSON Strin" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:41:59.640 | warn | (1215) Script "!# polling.fn 1.2 !# !# Dieses Script gibt die Werte  aller Systemvariablen als J" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:41:29.682 | warn | (1215) Script "!# programs.fn 1.3 !# Dieses Script gibt eine Liste der  Programme als JSON Strin" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:41:29.640 | warn | (1215) Script "!# polling.fn 1.2 !# !# Dieses Script gibt die Werte  aller Systemvariablen als J" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:40:59.682 | warn | (1215) Script "!# programs.fn 1.3 !# Dieses Script gibt eine Liste der  Programme als JSON Strin" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:40:59.639 | warn | (1215) Script "!# polling.fn 1.2 !# !# Dieses Script gibt die Werte  aller Systemvariablen als J" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:40:29.678 | warn | (1215) Script "!# programs.fn 1.3 !# Dieses Script gibt eine Liste der  Programme als JSON Strin" ignored, because still pending.
hm-rega.0 | 2020-05-26 05:40:29.638 | warn | (1215) Script "!# polling.fn 1.2 !# !# Dieses Script gibt die Werte  aller Systemvariablen als J" ignored, because still pending.

**Comment by foxriver76** [comment]
Hm irgendwie gehen wohl die Antworten der CCU verloren oder sie sendet einfach nie welche, damit bleiben die rega Anfragen in der eigenen Warteschlange hängen. Die Anfragen haben nun einen Timeout von 15 Sekunden, wenn dieser erreicht wird, wird die Anfrage abgebrochen.

**Comment by aba320** [comment]
Hallo i have still a lot of entries in my log 
rega: 3.0.16 js: 12.22.1 raspimatic: `3.57.5.20210525` 
`


hm-rega.0 | 2021-05-29 09:56:43.382 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
-- | -- | -- | --
hm-rega.0 | 2021-05-29 09:55:57.806 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
host.raspberrypiiobroker | 2021-05-29 09:55:49.864 | info | Updating repository "Stable (default)" under "http://download.iobroker.net/sources-dist.json"
hm-rega.0 | 2021-05-29 09:51:52.746 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:51:41.064 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:51:41.063 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:51:41.063 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:51:41.062 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:51:41.061 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:46:52.798 | warn | (698) Script "!# system.fn 0.1 !# !# Dieses Script gibt die FW-Versionsnummer und mehr systems" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:46:49.969 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:46:49.969 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:46:49.968 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:46:49.968 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:46:48.533 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:46:48.532 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
host.raspberrypiiobroker | 2021-05-29 09:45:08.763 | info | instance system.adapter.dwd.1 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.raspberrypiiobroker | 2021-05-29 09:45:08.018 | info | instance system.adapter.dwd.0 terminated with code 11 (ADAPTER_REQUESTED_TERMINATION)
host.raspberrypiiobroker | 2021-05-29 09:45:04.266 | info | instance system.adapter.dwd.1 started with pid 16532
host.raspberrypiiobroker | 2021-05-29 09:45:00.215 | info | instance system.adapter.dwd.0 started with pid 16360
host.raspberrypiiobroker | 2021-05-29 09:41:56.710 | warn | Server Objects 127.0.0.1:59754 Error from InMemDB: Error: Not exists
hm-rega.0 | 2021-05-29 09:41:53.264 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:41:53.263 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:41:43.528 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:36:51.932 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:36:50.648 | warn | (698) Script "!# system.fn 0.1 !# !# Dieses Script gibt die FW-Versionsnummer und mehr systems" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:36:43.628 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:36:43.628 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.
hm-rega.0 | 2021-05-29 09:36:43.627 | warn | (698) Script "!# dutycycle.fn 0.3 string stderr; string stdout; system.Exec("/bin/sh -c '" # '" ignored, because still pending.



`
