### ISSUE TITLE
Adapter not working when WebUI using different port than 80

### ISSUE THREAD

**Issue by kalledausb** [ioBroker/ioBroker.hm-rega#117]
When changing WebUI Port of Homematic Installation adapter status stays yellow. Log says ReGaHss down.

I think I found the problem, line 47 in rega.js:
                url: `${this.protocol + this.options.ccuIp}/ise/checkrega.cgi`,

When I manually add my port there it works.

Maybe an option to add a custom port is needed?

**Comment by foxriver76** [comment]
Port 80 ist of course standard HTTP port and will be automatically used when no port provided. You are the first one, who has such a setup, thus I guess it will introduce more confusion when I add an extra option in GUI, however, I can provide you a solution in the next release.

**Comment by kalledausb** [comment]
I agree that it is an edge case, maybe sth similar like the Rega API Port change through CLI could be a solution.

Maybe some more users will run into it in future, my setup is debmatic on an all-in-one homeserver (most apps containerized) and port 80 already in use by pi-hole.

**Comment by Rooby69** [comment]
I had the same issue and after long time I found this. Would be nice if there would be apossibility to change the port onthe rega adapter. I run depmatic and ioBroker on a raspberry and I want to useport 80 for something different.

**Comment by foxriver76** [comment]
https://github.com/ioBroker/ioBroker.hm-rega#my-ccu-webinterface-has-a-different-port-than-the-standard-httphttps-protocols-thus-no-connection-is-established-how-can-i-configure-the-adapter-to-use-a-custom-port-for-the-webinterface

**Comment by kalledausb** [comment]
3.0.18 seems to break this fix - I had the same issue, resolved when downgrading to 3.0.17 and happening again when upgrading again to 3.0.18

**Comment by foxriver76** [comment]
can you show me your system.adapter.hm-Rega.x object when on 3.0.18

**Comment by kalledausb** [comment]
Sorry, didn't get what to show. In the objects tab there seems to be not much useful info for hm-rega.0 adapter.
Log after upgrade shows (like before this fix was implemented):
![iob_rega](https://user-images.githubusercontent.com/44480199/115070035-b1f89800-9ef4-11eb-8c15-5499930bf49e.png)

**Comment by foxriver76** [comment]
Okay German interface.

Du gehst z. B. ins Terminal auf dem Rechner, auf welchem der ioBroker läuft und führst dort `iob object get system.adapter.hm-rega.0`, aus oder Objekte und suchst das Objekt dort (benötigt evtl. Expertenmodus), hinten auf den Stift dann Tab raw. Falls du Auth an hast, bitte Nutzer und PW unkenntlich machen.

**Comment by kalledausb** [comment]
Ah, verstanden, danke:
[rega_object.txt](https://github.com/ioBroker/ioBroker.hm-rega/files/6327406/rega_object.txt)

**Comment by foxriver76** [comment]
Ah. konnte es nachstellen 3.0.19 hat fixt es, sorry fürs kaputt machen ;-)

**Comment by kalledausb** [comment]
Prima, 3.0.19 passt auch bei mir wieder, vielen Dank!

**Comment by iaktern** [comment]
Hi, thanks for allowing to change the WebUI port! I had already given up on getting this adapter to work until i stumbled across this issue. Now it works! (I also have the setup of iobroker and debmatic on a raspi, so I want to use port 80/443 for another app)

It is really great that you can configure the port via the cli, but I would also pledge for putting it in the GUI. I have to admit, that I can not understand your argumentation that such a setting will cause confusion: 
1. in my experience using iobroker is only for "experienced" users. All of these guys probably know what a port is and why someone would change it, 
2. `hm-rega` is probably used in combination with `hm-rpc` - and this adapter allows to set a different port in the GUI

I'm also not quite sure that the assumption is correct that this setting is uncommon and only used by one of 10000 users. I think one main advantage of iobroker is that you are able to avoid tons of gateways in your home with solutions like debmatic and deconz. Having all the solutions installed on one machine requires to reconfigure port 80/443. 

And another plus for having that option inside the GUI: I gave up installing this adapter since the log message just stated the CCU is unreachable. Connection issues can arise from so many situations and after trying to change some things, I gave up. I needed some time to understand the CCU architecture and to realize that it could probably result from the changed WebUI port. If there would have been an option inside the GUI, I probably would have found the solution way earlier.

Nonetheless, thanks for the adapter and the option. It is only my opinion that a setting in the GUI would be useful.
