### ISSUE TITLE
Sticky Unreach information  will not be reset under objects even if there is already reset in CCU

### ISSUE THREAD

**Issue by smartboart** [ioBroker/ioBroker.hm-rega#50]
Hello ,
The Sticky Unreach information will not be reset automatically under objects even if it is already reset in CCU. The state still stands on true.

**Comment by foxriver76** [comment]
Do you mean the state UNREACH or the state UNREACH_ALARM?

**Comment by foxriver76** [comment]
If you mean the alarm state, I can confirm this. It seems like the script to read alarms shows state 2 for solved alarms, like:
```
    "1321": {
        "Name": "AL-OEQ1197840%3A0.CONFIG_PENDING",
        "AlState": 2,
        "AlOccurrenceTime": "2019-01-24 15:02:20",
        "LastTriggerTime": "2019-01-24 15:05:27",
        "Operations": 5,
        "AlTriggerDP": 1320,
        "Parent": 1318
    }
```

and state 1 for an currently present alarm. But the code in rega seems like it has been implemented to interpret 0 as no alarm and everything else as an active alarm by using 

```javascript
            const state = {
                val: !!data[dp].AlState,
                ack: true,
                lc: new Date(data[dp].AlOccurrenceTime),
                ts: new Date(data[dp].LastTriggerTime)
            };
```

Unfortunately I am not able to find more information about AlState: 2 so I can only assume that it says: Once there was an alarm. So I would suggest to set the alarm indicator to false if its !== 1

@smartboart please anyway give me an answer to my question to be sure. ;-)

**Comment by Apollon77** [comment]
The idea of the (iobroker onw) ALARM states is to use them as "true" trigger option when it happends. They are not supporsed to be reset

**Comment by smartboart** [comment]
OK,  understand... I mean sticky unreach and sticky unreach alarm... I trigger with this state a counting script to see which hardware seems to have some trouble... So I would be happy to have this information as a trigger in both directions... I mean I also want to know if the problem is acknowledged and not present anymore... For my opinion it makes sense to update this states also...

**Comment by foxriver76** [comment]
Yes, e. G. the UNREACH state should work like this (not the UNREACH_ALARM). Tested it Config pending state today and it worked as expected.

**Comment by foxriver76** [comment]
@Apollon77 I still think there is something wrong with the implementation of alarms. Maybe the following example helps:

1. I took out the battery of one of my devices and changed config to create a config pending message
2. ioB polls alarms and recognizes alarm state (1) --> ioB changes related alarm to true
3. I set the realated alarm in ioB to false, this triggers the acknowledgeAlarm function --> service message is gone in CCU
4. Alarm script polls --> now the config pending alarm state is 2 by the rega script (which MAYBE means, the alarm has been acknowledged), due to the fact, that the adapter interprets a 2 as true, my alarm state is again set to true in ioB, but the service message is already gone
5. so I would still expect that a 2 not means alarm should be set to true

I know you are also not deep in this alarm meachanics, but as it is implemented at the moment, it makes no sense for me.

**Comment by foxriver76** [comment]
Added documentation + reworked the alarm states as described here https://github.com/ioBroker/ioBroker.hm-rega#what-are-the-alarm-states-created-in-the-devices-object in https://github.com/ioBroker/ioBroker.hm-rega/commit/d6c775edb705018617b87f0204f3df2be6cc2238

**Comment by Apollon77** [comment]
Colm I even did not knew that :-)
