### ISSUE TITLE
after restart, manually assigned objects removed from room enum

### ISSUE THREAD

**Issue by Scrounger** [ioBroker/ioBroker.hm-rega#71]
I assigned other objects to rooms created by hm-rega adapter:
![room](https://user-images.githubusercontent.com/6370451/64149349-03d6d200-ce26-11e9-9ad4-d3be3a0fb86e.png)

after adapter restart, these assigned objects will be removed from room enum:
![room_after_restart](https://user-images.githubusercontent.com/6370451/64149379-194bfc00-ce26-11e9-9fe8-4ac769bc9f81.png)

**Comment by DutchmanNL** [comment]
looks like a relation with https://github.com/ioBroker/ioBroker.hm-rega/issues/70

but this time rooms are affected,  confirmed version 2.4.7

**Comment by DutchmanNL** [comment]
and I think directly related to https://github.com/ioBroker/ioBroker.hm-rega/issues/34

**Comment by foxriver76** [comment]
Was due to this automatic sync stuff and the desire that when you remove something in CCU from Enums, it also ends up in ioB. However, I have tested on hm-rega and hm-rpc in the code and of course hm-rega cannot even be added to the CCU. Thus, the code assumed that all hm-rega vars have been deleted on CCU side from the enum. Is now fixed.
